services:
  accounts:
    image: "kamlatiwari/accounts:v1"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mybank_network
  loans:
    image: "kamlatiwari/loans:v1"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mybank_network
  cards:
    image: "kamlatiwari/cards:v1"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mybank_network
networks:
  mybank_network:
    driver: "bridge"